"""Source registry for compliant tipster ingestion v2.

This file is intentionally opinionated: sources are selected for auditable,
public, repeatable extraction quality, not for popularity. All sources remain
shadow-only until a repo-local robots/ToS review artifact exists.
"""
from __future__ import annotations

from .contracts import SourcePolicy, SourceTier

SOURCES: dict[str, SourcePolicy] = {
    # CORE PRODUCTION-CANDIDATE SOURCES
    "sportsgambler": SourcePolicy(
        source_id="sportsgambler",
        display_name="Sportsgambler",
        base_url="https://www.sportsgambler.com",
        tier=SourceTier.HTML_STATIC,
        sports=("football", "tennis", "basketball", "hockey", "volleyball"),
        entrypoints=("https://www.sportsgambler.com/betting-tips/football/",),
        allow_playwright=False,
        max_pages_per_run=8,
        min_delay_seconds=3.0,
        parser_strategy="article_narrative_html",
        data_role="narrative_team_news_stats",
        affiliate_bias_risk="medium_high",
        production_status="production_candidate_after_robots_terms_fixture_review",
        notes="Best narrative source: match previews, team news/injuries/lineups/form/xG-style rationale. HTTP-first only; never follow /r/, odds.php, sportsbook go-links, login or commercial redirects.",
    ),
    "forebet": SourcePolicy(
        source_id="forebet",
        display_name="Forebet",
        base_url="https://www.forebet.com",
        tier=SourceTier.HTML_STATIC,
        sports=("football",),
        entrypoints=("https://www.forebet.com/en/football-tips-and-predictions-for-today",),
        allow_playwright=False,
        max_pages_per_run=4,
        min_delay_seconds=3.0,
        parser_strategy="forebet_table",
        data_role="structured_model_probabilities_score",
        affiliate_bias_risk="medium",
        production_status="fixture_snapshot_only_manual_review_no_live_fetch",
        notes="Structured table source: 1X2 probabilities, prediction, correct score, average goals, weather/odds context. Live fetch is blocked after observed robots restrictions; keep parser for fixture snapshots and manual review only.",
    ),
    "predictz": SourcePolicy(
        source_id="predictz",
        display_name="PredictZ",
        base_url="https://www.predictz.com",
        tier=SourceTier.HTML_STATIC,
        sports=("football",),
        entrypoints=("https://www.predictz.com/predictions/",),
        allow_playwright=False,
        max_pages_per_run=6,
        min_delay_seconds=3.0,
        parser_strategy="predictz_fixture_table",
        data_role="form_odds_winner_btts_ou_score",
        affiliate_bias_risk="medium",
        production_status="fixture_snapshot_only_manual_review_no_live_fetch",
        notes="Daily tips with match winner odds, last-5 form, BTTS, O/U 2.5 and correct-score pages. Observed robots/live-fetch restrictions keep this source fixture-snapshot-only pending manual review.",
    ),
    "windrawwin": SourcePolicy(
        source_id="windrawwin",
        display_name="WinDrawWin",
        base_url="https://www.windrawwin.com",
        tier=SourceTier.HTML_STATIC,
        sports=("football",),
        entrypoints=("https://www.windrawwin.com/predictions/",),
        allow_playwright=False,
        max_pages_per_run=6,
        min_delay_seconds=3.0,
        parser_strategy="league_prediction_tables",
        data_role="broad_league_coverage_stats_backed_tips",
        affiliate_bias_risk="medium",
        production_status="production_candidate_after_robots_terms_fixture_review",
        notes="Very broad league/date coverage, with statistics pages for BTTS, O/U, corners etc. Use for cross-source event/market agreement.",
    ),
    "feedinco": SourcePolicy(
        source_id="feedinco",
        display_name="Feedinco",
        base_url="https://www.feedinco.com",
        tier=SourceTier.HTML_STATIC,
        sports=("football", "tennis", "basketball", "cricket", "esports"),
        entrypoints=("https://www.feedinco.com/tips/",),
        allow_playwright=False,
        max_pages_per_run=5,
        min_delay_seconds=3.0,
        parser_strategy="public_tips_index_and_detail",
        data_role="multi_market_multi_sport_tip_index",
        affiliate_bias_risk="high",
        production_status="shadow_candidate_high_noise",
        notes="Good breadth: football, tennis, eSports, daily tips, BTTS, O/U, correct score, acca. High affiliate/noise surface; strict garbage filters and date validation required.",
    ),
    "bettingclosed": SourcePolicy(
        source_id="bettingclosed",
        display_name="BettingClosed",
        base_url="https://www.bettingclosed.com",
        tier=SourceTier.HTML_STATIC,
        sports=("football",),
        entrypoints=("https://www.bettingclosed.com/predictions/",),
        allow_playwright=False,
        max_pages_per_run=5,
        min_delay_seconds=3.0,
        parser_strategy="competition_prediction_index",
        data_role="country_competition_counts_prediction_index",
        affiliate_bias_risk="medium_high",
        production_status="shadow_candidate_requires_js_loading_review",
        notes="Useful country/competition prediction index, but public page shows loading markers and VIP/login links. Keep shadow until fixture snapshots prove stable non-JS extraction.",
    ),
    "zawodtyper": SourcePolicy(
        source_id="zawodtyper",
        display_name="ZawodTyper",
        base_url="https://www.zawodtyper.pl",
        tier=SourceTier.HTML_DYNAMIC,
        sports=("football", "tennis", "basketball", "volleyball", "hockey"),
        entrypoints=("https://www.zawodtyper.pl/",),
        allow_playwright=False,
        allow_xhr_capture=True,
        max_pages_per_run=3,
        min_delay_seconds=5.0,
        parser_strategy="public_np_ajax_json",
        data_role="legacy_tipster_claims_with_accuracy_context",
        affiliate_bias_risk="medium_high",
        production_status="shadow_live_candidate_public_read_xhr",
        notes="Public read-only same-origin NP_ajax.php transport reviewed for shadow live use. Fetch daily public page first, use no-cookie replay when certified, reject auth/session/private cookies, never use Playwright in production or bookmaker redirects.",
    ),
    "typersi": SourcePolicy(
        source_id="typersi",
        display_name="Typersi",
        base_url="https://typersi.pl",
        tier=SourceTier.HTML_DYNAMIC,
        sports=("football", "tennis", "basketball", "volleyball", "hockey"),
        entrypoints=("https://typersi.pl/",),
        allow_playwright=False,
        max_pages_per_run=0,
        min_delay_seconds=5.0,
        parser_strategy="legacy_bridge_only",
        data_role="legacy_public_tipster_claims",
        affiliate_bias_risk="medium_high",
        production_status="legacy_candidate_requires_compliance_certification",
        notes="Legacy canonical S2 source currently parsed only through generic DOM/HTML heuristics. Keep as registry-visible legacy candidate, not an automatic v2 fetch target.",
    ),
    # SHADOW / RESEARCH SOURCES
    "betmines": SourcePolicy(
        source_id="betmines",
        display_name="BetMines",
        base_url="https://betmines.com",
        tier=SourceTier.HTML_DYNAMIC,
        sports=("football",),
        entrypoints=("https://betmines.com/football-predictions-today", "https://betmines.com/"),
        allow_playwright=False,
        max_pages_per_run=3,
        min_delay_seconds=5.0,
        parser_strategy="shadow_dynamic_public_text_only",
        data_role="ai_probabilities_statistics",
        affiliate_bias_risk="medium",
        production_status="research_only_dynamic_auth_surfaces",
        notes="Strong data story: AI probabilities, >150 leagues, stats and unavailable players. Page exposes auth/filter surfaces and dynamic content; no production scraper until public fixture contract exists.",
    ),
    "sportytrader": SourcePolicy(
        source_id="sportytrader",
        display_name="SportyTrader",
        base_url="https://www.sportytrader.com",
        tier=SourceTier.HTML_STATIC,
        sports=("football", "tennis", "basketball"),
        entrypoints=("https://www.sportytrader.com/en/betting-tips/football/",),
        allow_playwright=False,
        max_pages_per_run=3,
        min_delay_seconds=5.0,
        parser_strategy="shadow_article_preview",
        data_role="expert_preview_stats_lineups",
        affiliate_bias_risk="medium_high",
        production_status="research_only_next_phase",
        notes="Good preview/stats/lineup text; not part of v2 core to keep first implementation small and auditable.",
    ),
    # MANUAL REVIEW / DO NOT SCRAPE BY DEFAULT
    "pickswise": SourcePolicy(
        source_id="pickswise",
        display_name="PicksWise",
        base_url="https://www.pickswise.com",
        tier=SourceTier.MANUAL_REVIEW,
        sports=("football", "tennis", "basketball", "hockey"),
        entrypoints=("https://www.pickswise.com/",),
        allow_playwright=False,
        max_pages_per_run=0,
        parser_strategy="manual_review_only",
        data_role="expert_picks_major_us_sports",
        affiliate_bias_risk="high",
        production_status="legacy_manual_review_dynamic_affiliate_sensitive",
        notes="Legacy S2 source retained for audit completeness. Valuable expert-pick brand, but dynamic/content-policy uncertainty and affiliate surface keep it out of automatic v2 live fetch.",
    ),
    "betideas": SourcePolicy(
        source_id="betideas",
        display_name="BetIdeas",
        base_url="https://www.betideas.com",
        tier=SourceTier.MANUAL_REVIEW,
        sports=("football", "tennis", "basketball", "hockey", "volleyball"),
        entrypoints=("https://www.betideas.com/",),
        allow_playwright=False,
        max_pages_per_run=0,
        parser_strategy="manual_review_only",
        data_role="legacy_match_preview_claims",
        affiliate_bias_risk="high",
        production_status="legacy_manual_review_dynamic_affiliate_sensitive",
        notes="Legacy S2 source retained for audit completeness. Dynamic listing/detail behavior and affiliate sensitivity require manual review before any compliant fetch design.",
    ),
    "olbg": SourcePolicy(
        source_id="olbg",
        display_name="OLBG",
        base_url="https://www.olbg.com",
        tier=SourceTier.MANUAL_REVIEW,
        sports=("football", "tennis", "basketball", "hockey", "horse_racing"),
        entrypoints=("https://www.olbg.com/betting-tips",),
        allow_playwright=False,
        max_pages_per_run=0,
        parser_strategy="manual_review_only",
        data_role="community_tipster_rankings",
        affiliate_bias_risk="high",
        production_status="manual_review_only",
        notes="Community data is valuable but path-level restrictions/API/tipster areas need legal review. Do not scrape by default.",
    ),
    "bettingexpert": SourcePolicy(
        source_id="bettingexpert",
        display_name="bettingexpert",
        base_url="https://www.bettingexpert.com",
        tier=SourceTier.MANUAL_REVIEW,
        sports=("football", "tennis", "basketball", "hockey"),
        entrypoints=("https://www.bettingexpert.com/",),
        allow_playwright=False,
        max_pages_per_run=0,
        parser_strategy="manual_review_only",
        data_role="community_tips_rankings",
        affiliate_bias_risk="high",
        production_status="manual_review_only",
        notes="Community-tipster source; dynamic and terms-sensitive. Research only; no production scraper until reviewed.",
    ),
}

CORE_SOURCE_IDS = ("sportsgambler", "forebet", "predictz", "windrawwin", "feedinco", "bettingclosed")
CERTIFIED_SHADOW_SOURCE_IDS = ("zawodtyper",)
RESEARCH_SOURCE_IDS = ("betmines", "sportytrader")
LEGACY_SOURCE_IDS = ("zawodtyper", "typersi", "pickswise", "betideas")
MANUAL_REVIEW_SOURCE_IDS = ("pickswise", "betideas", "olbg", "bettingexpert")
