#!/usr/bin/env python3
"""Fit config/sofa_settleability.json: the (competition, market family) cells
CONFIDENCE refuses NOT_SETTLEABLE (plan 2026-10-05, F0.6).

Between days only, like every fit (CLAUDE.md: never mid-day): it changes
which legs a build selects. Reads the printed legs of the days
[--from, --before) whose D+``horizon`` has passed by 00:00Z of --before, and
the DB read-only (bet.sofa.settleability.day_states). A cell is listed when
at least MIN_LEGS of its legs were judged and the Wilson 95% lower bound of
the share unsettled at D+3 for want of the statistic exceeds
MAX_UNSETTLED_LOWER (settleability.fit_refusals). The evidence and the
choice of the two dials: docs/sofa/evidence/settleability_2026-10-05.md.

    PYTHONPATH=src:. .venv/bin/python scripts/sofa/fit_settleability.py \\
        --before 2026-10-06 [--from 2026-09-19] [--dry-run]

Exit 0 OK, 2 on failure (no DB, --before in the future).
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

_REPO = Path(__file__).resolve().parents[2]
for _p in (str(_REPO), str(_REPO / "src")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from bet.sofa import settleability as st  # noqa: E402
from bet.sofa.atomic import write_atomic  # noqa: E402
from bet.sofa.config import SofaConfig  # noqa: E402
from bet.sofa.fit_meta import fit_stamp  # noqa: E402
from bet.sofa.timeutil import now  # noqa: E402

DOC = (
    "(competition_id, family) cells whose printed legs were not graded by the "
    "end of D+3 (UTC) for want of the statistic, often enough that the Wilson "
    "95% lower bound of that share exceeds max_unsettled_lower on at least "
    "min_legs judged legs. CONFIDENCE refuses a leg in a listed cell "
    "NOT_SETTLEABLE from epochs.SETTLEABILITY_FROM_UTC. Generated by "
    "scripts/sofa/fit_settleability.py --before <d>; never hand-edited, never "
    "re-fitted mid-day."
)


def closed_days(start: str, before: str, horizon_days: int) -> list[str]:
    """Days in [start, before) whose D+horizon ended by 00:00Z of `before`."""
    cut = datetime.strptime(before, "%Y-%m-%d").replace(tzinfo=UTC)
    last = (cut - timedelta(days=1)).strftime("%Y-%m-%d")
    if last < start:
        return []
    return [d for d in st.date_range(start, last)
            if st.horizon_end(d, horizon_days) <= cut]


def build_doc(
    states: list[st.LegState],
    *,
    before: str,
    start: str,
    days: list[str],
    horizon_days: int,
    min_legs: int,
    max_unsettled_lower: float,
    stamp: dict[str, Any],
) -> dict[str, Any]:
    refused = st.fit_refusals(
        states, min_legs=min_legs, max_unsettled_lower=max_unsettled_lower)
    total = st.Tally()
    for s in states:
        total.add(s)
    return {
        "_doc": DOC,
        "fitted_from": {
            "before": before,
            "from": start,
            "days": days,
            "horizon_days": horizon_days,
            "min_legs": min_legs,
            "max_unsettled_lower": max_unsettled_lower,
            "legs_printed": total.printed,
            "legs_judged": total.judged,
            "legs_data_unsettled": total.data_unsettled,
            "never_mid_day": True,
            **stamp,
        },
        "refused": refused,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--before", required=True,
                    help="fit on days strictly before this date (UTC)")
    ap.add_argument("--from", dest="start", default=None,
                    help="first day read (default: --before minus 28 days)")
    ap.add_argument("--horizon-days", type=int, default=st.DEFAULT_HORIZON_DAYS)
    ap.add_argument("--min-legs", type=int, default=st.MIN_LEGS)
    ap.add_argument("--max-unsettled-lower", type=float,
                    default=st.MAX_UNSETTLED_LOWER)
    ap.add_argument("--out", default=None,
                    help="output path (default config/sofa_settleability.json)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    today = now().astimezone(UTC).strftime("%Y-%m-%d")
    if args.before > today:
        print(f"REFUSED: --before {args.before} is after today ({today}); a fit "
              "reads finished days only", file=sys.stderr)
        return 2
    start = args.start or (
        datetime.strptime(args.before, "%Y-%m-%d") - timedelta(days=28)
    ).strftime("%Y-%m-%d")
    config = SofaConfig.from_env()
    runs_dir = Path(config.runs_dir)
    days = closed_days(start, args.before, args.horizon_days)
    try:
        conn = sqlite3.connect(
            f"file:{Path(config.db_path).resolve()}?mode=ro", uri=True)
        first = st.first_graded_times(st.load_regrade_logs(runs_dir))
        states = [s for d in days
                  for s in st.day_states(conn, runs_dir, d, first, args.horizon_days)]
        stamp = fit_stamp(conn)
    except sqlite3.Error as exc:
        print(f"FAILED: {exc}", file=sys.stderr)
        return 2
    doc = build_doc(
        states, before=args.before, start=start, days=days,
        horizon_days=args.horizon_days, min_legs=args.min_legs,
        max_unsettled_lower=args.max_unsettled_lower, stamp=stamp,
    )
    out = Path(args.out) if args.out else st.DEFAULT_SETTLEABILITY
    if not args.dry_run:
        write_atomic(out, json.dumps(doc, indent=1, ensure_ascii=False) + "\n")
    print("SOFA_SUMMARY: " + json.dumps({
        "stage": "FIT_SETTLEABILITY",
        "verdict": "OK",
        "dry_run": args.dry_run,
        "output_path": str(out),
        "metrics": {
            "days": len(days),
            "legs_judged": doc["fitted_from"]["legs_judged"],
            "refused_cells": len(doc["refused"]),
        },
    }), flush=True)
    for e in doc["refused"]:
        print(f"REFUSE {e['competition_name']} [{e['competition_id']}] "
              f"{e['family']}: {e['data_unsettled']}/{e['judged']} "
              f"(wilson_lo {e['wilson_lo']:.3f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
