"""Fit the list of Sofascore tournaments that never serve /event/{id}/statistics.

Deliberately OUTSIDE `DEFAULT_SEQUENCE`, for the same reason `fit_constants.py`
is: it reads the accumulated cache and rewrites a config file, and doing that
mid-day would change what a run costs while the run is measuring itself.

Reads only `data/sofa.db` — no live request is made. The evidence is the
statistics we already paid for: `sofa_event_stats.statistics_json IS NULL` is
the row we wrote after Sofascore answered 404, and the listing payload in
`sofa_entity_events` carries the tournament each of those events belonged to.

The gate is deliberately strict — MIN_EVENTS observations and not one of them
carrying statistics. Measured over 35,815 cached events on 2026-09-22 that
selects 53 tournaments and 1,241 requests a run, and loses **zero** real
observations. Loosening it to a 5% hit rate would buy 374 more requests and
start costing samples; that trade is not obviously worth making, and an
exclusion nobody measured is a coverage cut wearing the costume of a saving
(the same warning `board.load_excluded_tournament_ids` carries).
"""

from __future__ import annotations

import json
import sqlite3
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
OUT_PATH = ROOT / "config" / "sofa_no_stats_tournaments.json"

# How many cached events a tournament needs before its silence counts as a
# fact about the tournament rather than about the sample.
MIN_EVENTS = 10


def _tournament_of(event: dict[str, Any]) -> tuple[int | None, str]:
    tournament = event.get("tournament") or {}
    unique = tournament.get("uniqueTournament") or {}
    name = unique.get("name") or tournament.get("name") or "?"
    ident = unique.get("id")
    return (ident if isinstance(ident, int) else None), str(name)


def main() -> int:
    db_path = ROOT / "data" / "sofa.db"
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    has_stats: dict[int, bool] = {
        row["sofascore_event_id"]: bool(row["ok"])
        for row in conn.execute(
            "SELECT sofascore_event_id, statistics_json IS NOT NULL AS ok "
            "FROM sofa_event_stats"
        )
    }

    # One payload per event id; the same event appears in both teams' listings.
    payloads: dict[int, dict[str, Any]] = {}
    for row in conn.execute("SELECT events_json FROM sofa_entity_events"):
        try:
            data = json.loads(row["events_json"])
        except (TypeError, ValueError):
            continue
        events = data.get("events") if isinstance(data, dict) else data
        if not isinstance(events, list):
            continue
        for event in events:
            ident = event.get("id")
            if ident in has_stats and ident not in payloads:
                payloads[ident] = event

    tally: dict[int, list[int]] = defaultdict(lambda: [0, 0])  # id -> [with, without]
    names: dict[int, str] = {}
    for ident, event in payloads.items():
        tournament_id, name = _tournament_of(event)
        if tournament_id is None:
            continue
        names[tournament_id] = name
        tally[tournament_id][0 if has_stats[ident] else 1] += 1

    selected: list[dict[str, Any]] = sorted(
        (
            {"id": tid, "name": names[tid], "events": counts[1]}
            for tid, counts in tally.items()
            if counts[0] == 0 and counts[1] >= MIN_EVENTS
        ),
        key=lambda entry: -int(entry["events"]),
    )
    saved = sum(int(entry["events"]) for entry in selected)

    OUT_PATH.write_text(
        json.dumps(
            {
                "_doc": (
                    "uniqueTournament ids for which Sofascore has never served "
                    "/event/{id}/statistics. SAMPLES skips the request rather "
                    "than paying for a 404 it can predict. Generated by "
                    "scripts/sofa/fit_no_stats_tournaments.py from data/sofa.db; "
                    "never hand-edited, and never re-fitted mid-day. An event "
                    "whose own payload says hasEventPlayerStatistics is still "
                    "fetched, so a tournament that starts publishing is not "
                    "locked out until the next fit."
                ),
                "fitted_at_utc": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
                "min_events": MIN_EVENTS,
                "events_examined": len(payloads),
                "requests_saved_per_full_sample": saved,
                "tournaments": selected,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    print(
        f"FIT: {len(selected)} tournament(s), {saved} request(s) a full sample, "
        f"from {len(payloads)} cached events -> {OUT_PATH}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
